# db login
db:
  host: 127.0.0.1 # domain / localhost
  username: usr # database username
  password: false # database password, false if no password
  database: semiql # database name
  type: mysql # type of database (currently only mysql)

# general config
dashboard: true # enable statistics dashboard